import img from '../../../../Assets/images/testimonial3.jpg'
const Data = [
    { id: 1, name: "Kelian Anderson" , job: 'Selling Agents' ,img: img, desc: "Precious ipsum dolor sit amet consectetur adipisicing elit, sed dosmod tempor incididunt ut labore et dolore magna aliqua. quis nostrudPrecious ips um dolor sit amet, consecte Ut enim ad min veniam"},
    { id: 2, name: "Kelian Anderson" , job: 'Selling Agents' ,img: img, desc: "Precious ipsum dolor sit amet consectetur adipisicing elit, sed dosmod tempor incididunt ut labore et dolore magna aliqua. quis nostrudPrecious ips um dolor sit amet, consecte Ut enim ad min veniam"},
    { id: 3, name: "Kelian Anderson" , job: 'Selling Agents' ,img: img, desc: "Precious ipsum dolor sit amet consectetur adipisicing elit, sed dosmod tempor incididunt ut labore et dolore magna aliqua. quis nostrudPrecious ips um dolor sit amet, consecte Ut enim ad min veniam"},
    { id: 4, name: "Kelian Anderson" , job: 'Selling Agents' ,img: img, desc: "Precious ipsum dolor sit amet consectetur adipisicing elit, sed dosmod tempor incididunt ut labore et dolore magna aliqua. quis nostrudPrecious ips um dolor sit amet, consecte Ut enim ad min veniam"},
    { id: 5, name: "Kelian Anderson" , job: 'Selling Agents' ,img: img, desc: "Precious ipsum dolor sit amet consectetur adipisicing elit, sed dosmod tempor incididunt ut labore et dolore magna aliqua. quis nostrudPrecious ips um dolor sit amet, consecte Ut enim ad min veniam"},
    { id: 6, name: "Kelian Anderson" , job: 'Selling Agents' ,img: img, desc: "Precious ipsum dolor sit amet consectetur adipisicing elit, sed dosmod tempor incididunt ut labore et dolore magna aliqua. quis nostrudPrecious ips um dolor sit amet, consecte Ut enim ad min veniam"},
    { id: 7, name: "Kelian Anderson" , job: 'Selling Agents' ,img: img, desc: "Precious ipsum dolor sit amet consectetur adipisicing elit, sed dosmod tempor incididunt ut labore et dolore magna aliqua. quis nostrudPrecious ips um dolor sit amet, consecte Ut enim ad min veniam"},
    { id: 8, name: "Kelian Anderson" , job: 'Selling Agents' ,img: img, desc: "Precious ipsum dolor sit amet consectetur adipisicing elit, sed dosmod tempor incididunt ut labore et dolore magna aliqua. quis nostrudPrecious ips um dolor sit amet, consecte Ut enim ad min veniam"},
]
export default Data